### ISSUE TITLE
no response from board

### ISSUE THREAD

**Issue by andytwoods** [ThePiHut/rgbxmastree#7]
Hi, 
I've set up the board as specfied [here](https://thepihut.com/products/3d-rgb-xmas-tree-for-raspberry-pi?_pos=2&_sid=18cb1a022&_ss=r). Here's [pic](https://twitter.com/AndyTWoods/status/1205842871607341057), showing the board is correctly slotted in.
I run a python code example but I get no response from the board, and also no python error (although when I took the board out and ran the same code, I got no error).
I'm running the code within a heavily configured Raspian image: https://www.pyimagesearch.com/2016/11/21/raspbian-opencv-pre-configured-and-pre-installed/. Could this be an issue?
Best, Andy.

update: I tried the tree out on a different pi3 using the latest Raspian, and afraid it still does not light (and no warnings from Python).

**Comment by bennuttall** [comment]
What have you tried so far?

With `tree.py` downloaded, try opening a Python shell and typing:

```python
>>> from tree import *
>>> tree = RGBXmasTree()
>>> tree.on()
```

Does that work? If not, contact Pi Hut support.

**Comment by ajgbarnes** [comment]
I used the latest Raspbian Buster image from here which I know works:

https://downloads.raspberrypi.org/raspbian_full_latest

So worth eliminating your image just in case.

It's installed correctly as you remarked so that's good.  I'm hae successfully run mine on a Pi 3 B+ and Pi Zero W - haven't tried a 4 yet (I have one, just haven't tried it).

How are you running the program?  I created a new file with the python scripts in and run with e.g.

```
python3 sparkles.py
```

There isn't a lot that go wrong with those boards unless a track is cracked.  If you get another, snip it out of the frame if you didn't this time (don't bend it out).

**Comment by andytwoods** [comment]
Afraid I am totally failing to find contact details for pihut support (frustrating). They just provide twitter and Facebook contact details (tweeted them).

Real shame as I wanted to link up the tree with my emotion detection stuff I'm doing at work. 

Im using pi 3's. 

Im back at work on Thurs so will have a look for cracks. 

I am hoping that pihut see my tweet...

**Comment by ajgbarnes** [comment]
They have an email address too contact@thepihut.com and you can raise support tickets.

https://thepihut.com/pages/company-info
https://support.thepihut.com/hc/en-us/articles/115002048129-How-do-I-return-an-item-

Hope it works - mine seems to remember its last state when it powers up, until it resets when the python code runs.  When I first switched it on some random lights were on in white.

**Comment by resmithn** [comment]
Having same issue, no lights, tried another PI 3B+, still no lights. Tried the TreeOn code, no lights. Python Code seems to execute in Terminal, only error was Color versus color, Name not found in one of the scripts. Corrected that but still no lights. Submitted request to Pi Hut support, waiting for reply.
Thanks for the previous comments.

**Comment by bennuttall** [comment]
Have updated the script to turn the lights on if you run `tree.py` directly. If you're running that file and nothing's happening, and there's no error, contact The Pi Hut.

**Comment by resmithn** [comment]
Re-downloaded tree.py, no errors and no lights. Put in a request to Pi Hut.
Thanks for your help.

**Comment by bernardoleite** [comment]
Hi! Is there a solution ? I am also running tree.py and no lights (and no errors).

Thanks in advance.

Best regards

**Comment by resmithn** [comment]
I found that using a second 40pin header helped the connection to the Xmas
tree. Even some times after starting the script you have to "wiggle" the
tree to get connection and then lights come on. The second 40 pin header
worked for me. Hope this helps.

**Comment by bernardoleite** [comment]
> I found that using a second 40pin header helped the connection to the Xmas

Thanks for the reply resmithn. 

Did the lights on your tree turn on after using a second 40pin between the raspberry and the tree? Can you send me a picture? 
I can connect the tree directly to the raspberry without any problems. The problem is that the lights do not turn on after running the python scripts. I don't understand: s
Is there anything else I can do?

I have also contacted PiHut support.

Regards

**Comment by resmithn** [comment]
Below is picture from PI Hut website, make sure you have the tree inserted
correctly. As said: I had to wiggle the tree to get it to come on. The PI
has relatively short GPIO pins, so adding a 40 pin header [with longer
pins] solved the issue for me. Don't know where you are, but Amazon has 40
pin headers in a variety of sizes. Here is picture from PI Hut website:

Orientation - make sure you don't place the Xmas Tree on your Raspberry Pi
backwards! Power will go to the wrong places – and that’s just no fun at
Christmas! See image below for header orientation:
